services:
  - type: web
    name: poke-r-poker-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        value: redis://localhost:6379
    healthCheckPath: /health
